#pragma config(Sensor, S1,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S2,     compassSensor,  sensorI2CCustom)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          clawMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Authors: Stephen Kinser
					 Kris Brown
					 Ashley Eden Cox

Project 2: Part 1
Due: 03/23/15
*/

// Include drivers for multiplexer and light sensor
#include "drivers/hitechnic-sensormux.h"
#include "drivers/lego-ultrasound.h"
#include "drivers/lego-light.h"
#include "drivers/lego-touch.h"
#include "drivers/hitechnic-compass.h"
#include "motion.h"
#include "music.h"
// Define easy names for sensors connected to multiplexer
const tMUXSensor lightSensor = msensor_S1_4;	//Light sensor in smux port 4
const tMUXSensor  touchRight= msensor_S1_3;	//Touch right smux port 3
const tMUXSensor  touchLeft = msensor_S1_2; //Touch left smux port 2
const tMUXSensor ultrasonicSensor = msensor_S1_1; // Ultrasonic smux port 1



//declaring motor speeds
bool wall= false;
bool egg= false;
int compassReading;
int nestValue = 15;
int floorValue = 25;

task MoveTowardsEgg();
task DetectWall();
task Wander();
task StopAtEgg();
task PushEggTowardsNest();
/* ENABLE AND DISABLE FUNCTIONS---------------------------------------------------------
void enable(int pid)
{
	process_enable[pid] = process_priority[pid];
}

void disable(int pid)
{
	process_enable[pid] = 0;
}*/
/*-----------maybe a helper function like periodic turn to help the robot wander more effectively? */
/*void periodic_turn(int pid)
{
	while(true)
	{
		if( time100)
		{
			enable(pid);
			Right(pid);
			//msleep(500L); Use halt instead?
			Halt(pid);
			disable(pid);
			//msleep();
			Halt(pid);
		}
	}
}*/

/* THESE ARE THE MAIN TASKS AS DESCRIBED ON THE PROJECT DESCRIPTION---------------------- */
//this makes the robot wander
task Wander()
{
	//add in a loop for timer to make the robot stop program after a certain amount of time (nothing is found)
	ClearTimer(T1);
	//time10[T1] < 120000
	while(time10[T1] < 120000 /*&& wall == false*/)//2 minutes
	{
		//nMotorEncoder[leftMotor]=0; //not sure if need to reset periodically
		//nMotorEncoder[rightMotor]=0;
		int decision =random(100)%3;//%3 //explicit "don't reach the default case"
		switch(decision){ //goes in one of the 8 directions
			case 0:
				Forward(random(500)+250);
			break;
			case 1:
				Left(random(500) + 250, 45); //pass two arguments, the length of distance traveled and the turn radius
			break;
			case 2:
				Right(random(500) + 250, 45);
			break;
			default:
			nxtDisplayStringAt(0, 31, "error with random number generator");
			wait10Msec(1000);
			break;

	}
	}

	//enable(pid);
	//Forward();
}

//this makes the robot move towards the egg
//useing the ULTRASONIC_PORT to close the distance from robot to egg
task PushEggTowardsNest()
{
	//StopTask(MoveTowardsEgg);
	StopTask(StopAtEgg);
					nxtDisplayTextLine(0, "Task: Move Toward Nest");
					nxtDisplayCenteredTextLine(1, "------------------");
					nxtDisplayCenteredTextLine(2, "performing 180 degree turn");
					nSyncedMotors=synchBA;
					nSyncedTurnRatio= 150;
		while((compassReading + 180) %360 != HTMCsetTarget(compassSensor)){// hopefully do a 180 degree turn
					motor[rightMotor] = MOTOR_MAX;
					nxtDisplayCenteredTextLine(3, "Current:%4d", HTMCsetTarget(compassSensor));
					nxtDisplayCenteredTextLine(4, "Home:%4d", compassReading);
					nxtDisplayClearTextLine(3);
			}
			Halt();
			nxtDisplayClearTextLine(2);
			nxtDisplayClearTextLine(3);
			nxtDisplayClearTextLine(4);
			int currentFloor =LSvalNorm(lightSensor);
			while( currentFloor > nestValue+ 7){
					nxtDisplayClearTextLine(2);
					//nxtDisplayTextLine(0, "Task: Move Toward Nest");
					nxtDisplayCenteredTextLine(1, "------------------");
					nxtDisplayCenteredTextLine(2, "Current: %4d", currentFloor);
					nxtDisplayTextLine(3, "Nest Value: %4d", nestValue);
					nxtDisplayTextLine(4, "Floor Value: %4d", floorValue);
					Forward();

				 	currentFloor =LSvalNorm(lightSensor);
			}
			Halt();
			wait1Msec(1000);

			raiseArm();
			egg= false;
			Right(100, 45);
}
task MoveTowardsEgg()
{
	int distance = 10; // need to test value
	while(USreadDist(ultrasonicSensor) > distance){
		nxtDisplayCenteredTextLine(0, "Task:");
	 	nxtDisplayCenteredTextLine(1,  "Move Towards Egg" );
		nxtDisplayCenteredTextLine(2, "Range: %d",USreadDist(ultrasonicSensor));

		Right(15,100);
		int tempDistRight= USreadDist(ultrasonicSensor);

		Left(15,100);
		int tempDistLeft = USreadDist(ultrasonicSensor);
		Forward();

		if(tempDistRight < tempDistLeft) {
			Right(25, 100);

			//wait1Msec(10);
		}
		else {
			Left(25, 100);
			//wait1Msec(10);
	}
	nxtDisplayClearTextLine(2);
	}
	//lowerArm();
	nxtDisplayClearTextLine(0);
	nxtDisplayClearTextLine(1);
	StartTask(StopAtEgg);
}
/*this stops the robot when it hits the egg
we will be using values from the ULTRASONIC_PORT
when readings are negative or not in range, that means we have the egg
*/
task StopAtEgg()
{
	StopTask(MoveTowardsEgg);
		nxtDisplayCenteredTextLine(0, "Task:");
	 	nxtDisplayCenteredTextLine(1, "Stop At Egg" );
		nxtDisplayCenteredTextLine(2, "Lowering Arm" );
	symph5();

	wait1Msec(1000);
	lowerArm();
	egg=true;// assume it was sucessful for now
	nxtDisplayClearTextLine(0);
	nxtDisplayClearTextLine(1);
	nxtDisplayClearTextLine(2);
	StartTask(PushEggTowardsNest);
}

//this will make the robot push the egg towards the nest
//need compass values from COMPASS_PORT to find way back to nest

//this will makes the robot push the egg into the nest(blue zone)
//will be using the LIGHT_SENSOR to detect the colors of the nest and line to it


//this will detect a wall
//when LEFT_TOUCH_SENSOR or RIGHT_TOUCH_SENSOR is pressed?
//how do we tell the wall is different from the eggs?
task DetectWall()
{
	nxtDisplayTextLine(0, "Wall Not Detected");
	while( !TSreadState(touchLeft) && !TSreadState(touchRight)); //while this isn't detected, do nothing
		nxtDisplayClearTextLine(0);
		nxtDisplayTextLine(0, "Wall Detected");
		wait1Msec(100);
		//wall= true;// implicit stop used in wander function adn move towards egg function
		//Halt();//when detected stop
		//StopTask(Wander); //explicit stop all movement processes

		wait10Msec(200);// wait
		Backwards(50); //then backwards
		Right(50, 45);// turn to get out of the way
		Halt();
		//StartTask(Wander);
		//wall= false;

	//StartTask(Wander);
	 nxtDisplayClearTextLine(0);
}

//this is where all the functions are called
task main()
{
//symph5();
	//initialize because junk values are a thing
	nMotorEncoder[leftMotor]=0;
	nMotorEncoder[rightMotor]=0;
	nMotorEncoder[clawMotor]=0;

//StartTask(MoveTowardsEgg);
	//raiseArm();// make sure it starts out as "ready to use"


/*************************************************************
									Get the Nest Value
**************************************************************/

while (nNxtButtonPressed != 3) {
	 // The enter button has been pressed, switch
    // to the other mode
   // nxtDisplayClearTextLine(0);
    nxtDisplayClearTextLine(1);
    nestValue = LSvalNorm(lightSensor);// could use the "Norm value" too
    nxtDisplayTextLine(0, "Lego");
    nxtDisplayTextLine(1, "Nest Value: %4d", nestValue);
     wait1Msec(25);
  }
	wait1Msec(2000);

/*************************************************************
									Get the Floor Value
**************************************************************/

  while (nNxtButtonPressed != 3) {
	 // The enter button has been pressed, switch
    // to the other mode
    //nxtDisplayClearTextLine(0);
    nxtDisplayClearTextLine(1);
    floorValue = LSvalNorm(lightSensor);// could use the "Norm value" too
    nxtDisplayTextLine(0, "Lego");
    nxtDisplayTextLine(1, "Floor Value: %4d", floorValue);
     wait1Msec(25);
  }
	wait1Msec(2000);

/*************************************************************
									Get the Compass Value
**************************************************************/

while (nNxtButtonPressed != 3) {
	 // The enter button has been pressed, switch
    // to the other mode
    //nxtDisplayClearTextLine(0);
    nxtDisplayClearTextLine(1);
    compassReading = HTMCsetTarget(compassSensor);// could use the "Norm value" too
    nxtDisplayTextLine(0, "Lego");
    nxtDisplayTextLine(1, "Compass Value:" );
    nxtDisplayTextLine(2, "\t %4d", compassReading);
     wait1Msec(25);
  }
  wait1Msec(2000);
    nxtDisplayClearTextLine(0);
    nxtDisplayClearTextLine(1);
    nxtDisplayClearTextLine(2);

  /**********************************************************
  								Actually Start Task Here
  **********************************************************/

 // set to some logical expression later, preferrably a "We have completed the task" or I have pressed a button
							// this may be difficult without prior knowledge of the course
//Left(1,100);
//Right(100,150);
	//StartTask(DetectWall);
	//starWars();
  //raiseArm();
  //symph5();
	StartTask(MoveTowardsEgg);
	//StartTask(Wander);
  //StartTask(PushEggTowardsNest);
  //raiseArm();
  //wait10Msec(1000);
  //lowerArm();
while(true);

 /*
    while (!TSreadState(touchRight));
    StopTask(PushEggTowardsNest);
			StartTask(DetectWall);

    while (!TSreadState(touchRight));
			StopTask(DetectWall);
			StartTask(MoveTowardsEgg);

	while (!TSreadState(touchRight));
		StopTask(MoveTowardsEgg);
	StartTask(PushEggTowardsNest);

	while (!TSreadState(touchRight));
  StopTask(PushEggTowardsNest);
	StartTask(Wander);
*/
	 // set to some logical expression later, preferrably a "We have completed the task" or I have pressed a button
		// this may be difficult without prior knowledge of the course
}	//StopAllTasks();
