#pragma config(Sensor, S1,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S2,     compassSensor,  sensorI2CCustom)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          clawMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Authors: Stephen Kinser
					 Kris Brown
					 Ashley Eden Cox

Project 2: Part 1
Due: 03/23/15
*/

// Include drivers for multiplexer and light sensor
#include "drivers/hitechnic-sensormux.h"
#include "drivers/lego-ultrasound.h"
#include "drivers/lego-light.h"
#include "drivers/lego-touch.h"
#include "drivers/hitechnic-compass.h"

// Define easy names for sensors connected to multiplexer
const tMUXSensor lightSensor = msensor_S1_4;	//Light sensor in smux port 4
const tMUXSensor  touchRight= msensor_S1_3;	//Touch right smux port 3
const tMUXSensor  touchLeft = msensor_S1_2; //Touch left smux port 2
const tMUXSensor ultrasonicSensor = msensor_S1_1; // Ultrasonic smux port 1



//declaring motor speeds
int MOTOR_MAX = 50;
int MOTOR_MIN = -50;
bool wall= false;
bool egg= false;
int compassReading;
int nestValue = 15;
int floorValue = 25;

task MoveTowardsEgg();
task DetectWall();
task Wander();
task StopAtEgg();
task PushEggTowardsNest();
/*BASIC FUNCTIONS-------------------------------------------------------------------- */
//this moves the robot forwards
void Forward( int length)
{
	nSyncedMotors=synchAB;
	while(nMotorEncoder[leftMotor]< length){ //set to slaves later
	motor[rightMotor] = MOTOR_MAX;
	motor[leftMotor] = MOTOR_MAX;
}
}
void Forward( )
{
		//nSyncedMotors=synchAB;
	motor[rightMotor] = MOTOR_MAX;
	motor[leftMotor] = MOTOR_MAX;
}
//this moves the robot to the left
void Left( int length, int turnRadians)
{
	nSyncedMotors=synchBA;
	nSyncedTurnRatio= turnRadians;
	//	nxtDisplayCenteredTextLine(0, "%d",(nMotorEncoder[leftMotor]));
	//wait10Msec(10000);
	while(nMotorEncoder[leftMotor]<length){
	//motor[rightMotor] = MOTOR_MIN;
	motor[leftMotor] = MOTOR_MAX;
}
}
//this moves the robot right
void Right( int length, int turnRadians)
{
	nSyncedMotors=synchAB;
	nSyncedTurnRatio= turnRadians;
	while(nMotorEncoder[rightMotor]<length){
	motor[rightMotor] = MOTOR_MAX;
	//motor[leftMotor] = MOTOR_MIN;
}
}
//this moves the robot backwards
void Backwards( int length)
{
	nSyncedMotors=synchAB;
	while(nMotorEncoder[leftMotor]<length){
	motor[rightMotor] = MOTOR_MIN;
	//motor[leftMotor] = MOTOR_MIN;
	}
}
//this funciton halts the robot
void Halt()
{
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}
void raiseArm(){
	while(nMotorEncoder[clawMotor] <10){ //setting it to arbitrary value until can make an angle based assumption
	motor[clawMotor]= MOTOR_MIN;
}
}
void lowerArm(){
	while(nMotorEncoder[clawMotor] <10){ //setting it to arbitrary value until can make an angle based assumption
	motor[clawMotor]= MOTOR_MAX;
}
}
/* ENABLE AND DISABLE FUNCTIONS---------------------------------------------------------
void enable(int pid)
{
	process_enable[pid] = process_priority[pid];
}

void disable(int pid)
{
	process_enable[pid] = 0;
}*/
/*-----------maybe a helper function like periodic turn to help the robot wander more effectively? */
/*void periodic_turn(int pid)
{
	while(true)
	{
		if( time100)
		{
			enable(pid);
			Right(pid);
			//msleep(500L); Use halt instead?
			Halt(pid);
			disable(pid);
			//msleep();
			Halt(pid);
		}
	}
}*/

/* THESE ARE THE MAIN TASKS AS DESCRIBED ON THE PROJECT DESCRIPTION---------------------- */
//this makes the robot wander
task Wander()
{
	//add in a loop for timer to make the robot stop program after a certain amount of time (nothing is found)
	ClearTimer(T1);
	//time10[T1] < 120000
	while(time10[T1] < 120000 /*&& wall == false*/)//2 minutes
	{
		//nMotorEncoder[leftMotor]=0; //not sure if need to reset periodically
		//nMotorEncoder[rightMotor]=0;
		int decision =random(100)%3;//%3 //explicit "don't reach the default case"
		switch(decision){ //goes in one of the 8 directions
			case 0:
				Forward(random(500)+250);
			break;
			case 1:
				Left(random(500) + 250, 45); //pass two arguments, the length of distance traveled and the turn radius
			break;
			case 2:
				Right(random(500) + 250, 45);
			break;
			default:
			nxtDisplayStringAt(0, 31, "error with random number generator");
			wait10Msec(1000);
			break;

	}
	}

	//enable(pid);
	//Forward();
}

//this makes the robot move towards the egg
//useing the ULTRASONIC_PORT to close the distance from robot to egg
task PushEggTowardsNest()
{
	//StopTask(MoveTowardsEgg);
	StopTask(StopAtEgg);
		//while((compassReading + 180) %360 == SensorValue(compassSensor)/*&& wall == false*/){// hopefully do a 180 degree turn
			//		motor[rightMotor] = MOTOR_MAX;
		//	}
			while(LSvalNorm(lightSensor) < floorValue  ){

			   nxtDisplayClearTextLine(0);
    		 nxtDisplayTextLine(0, "%4d", LSvalNorm(lightSensor));
    			nxtDisplayTextLine(1, "Nest Value: %4d", nestValue);
    		  nxtDisplayTextLine(2, "Floor Value: %4d", floorValue);
					Forward(10);
    		  wait1Msec(1000);
			}

			raiseArm();
			egg= false;
			//Right(100, 45);
}
task MoveTowardsEgg()
{
	int distance = 10; // need to test value
	while(USreadDist(ultrasonicSensor) > distance){
		nxtDisplayCenteredTextLine(0, "Range: %d",USreadDist(ultrasonicSensor));
		Forward();

		//Right(1, 5);
		int tempDistRight= USreadDist(ultrasonicSensor);

		Left(1, 7);
		int tempDistLeft = USreadDist(ultrasonicSensor);
		wait1Msec(10);

		if(tempDistRight < distance) {
			Right(1, 10);
			wait1Msec(10);
		}
		else if (distance < tempDistLeft) {
			Right(1, 5);
			wait1Msec(10);
	}
	}
	//lowerArm();
	//Halt();
	StartTask(StopAtEgg);
}
/*this stops the robot when it hits the egg
we will be using values from the ULTRASONIC_PORT
when readings are negative or not in range, that means we have the egg
*/
task StopAtEgg()
{
	StopTask(MoveTowardsEgg);
	//Halt();
	wait10Msec(1000);
	//lowerArm();
	egg=true;// assume it was sucessful for now
	StartTask(PushEggTowardsNest);
}

//this will make the robot push the egg towards the nest
//need compass values from COMPASS_PORT to find way back to nest

//this will makes the robot push the egg into the nest(blue zone)
//will be using the LIGHT_SENSOR to detect the colors of the nest and line to it


//this will detect a wall
//when LEFT_TOUCH_SENSOR or RIGHT_TOUCH_SENSOR is pressed?
//how do we tell the wall is different from the eggs?
task DetectWall()
{
	nxtDisplayTextLine(0, "Wall Not Detected");
	while( !TSreadState(touchLeft) && !TSreadState(touchRight)); //while this isn't detected, do nothing
		nxtDisplayClearTextLine(0);
		nxtDisplayTextLine(0, "Wall Detected");
		wait1Msec(1000);
		//wall= true;// implicit stop used in wander function adn move towards egg function
		//Halt();//when detected stop
		//StopTask(Wander); //explicit stop all movement processes

		wait10Msec(200);// wait
		Backwards(50); //then backwards
		Right(50, 45);// turn to get out of the way
		Halt();
		//StartTask(Wander);
		//wall= false;

	//StartTask(Wander);
	 nxtDisplayClearTextLine(0);
}

//this is where all the functions are called
task main()
{

	//initialize because junk values are a thing
	nMotorEncoder[leftMotor]=0;
	nMotorEncoder[rightMotor]=0;
	nMotorEncoder[clawMotor]=0;

//StartTask(MoveTowardsEgg);
	//raiseArm();// make sure it starts out as "ready to use"




  /**********************************************************
  								Actually Start Task Here
  **********************************************************/
     nxtDisplayClearTextLine(0);
    nxtDisplayClearTextLine(1);
    nxtDisplayClearTextLine(2);

	//StartTask(detectOutOfBounds);
 // set to some logical expression later, preferrably a "We have completed the task" or I have pressed a button
							// this may be difficult without prior knowledge of the course
    Forward();
    while (!TSreadState(touchRight)){

			StartTask(DetectWall);

}
		StopTask(DetectWall);

    while (!TSreadState(touchRight)){

			StartTask(MoveTowardsEgg);

}
		StopTask(MoveTowardsEgg);


	while (!TSreadState(touchRight)){

	StartTask(PushEggTowardsNest);
}
  StopTask(PushEggTowardsNest);

	while (!TSreadState(touchRight)){

	StartTask(Wander);
}
	StopTask(Wander);



	 // set to some logical expression later, preferrably a "We have completed the task" or I have pressed a button
		// this may be difficult without prior knowledge of the course
}	//StopAllTasks();
